FROM node:22-alpine AS build
WORKDIR /app
#Frontend doesn't need build step for static HTML/CSS/JS

FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY frontend/ /usr/share/nginx/html/

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
